name: Deploy Awakening Site to A2 Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy via rsync over SSH
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 7822 -H az1-ss108.a2hosting.com >> ~/.ssh/known_hosts

          rsync -avz --delete \
            -e "ssh -p 7822 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
            ./dist/ youruser@az1-ss108.a2hosting.com:~/public_html/awakening/
